ALTER TABLE zones ADD COLUMN IF NOT EXISTS delivery_fee_type VARCHAR(20) DEFAULT 'flat';
ALTER TABLE zones ADD COLUMN IF NOT EXISTS base_delivery_fee_paise INTEGER DEFAULT 2500;
ALTER TABLE zones ADD COLUMN IF NOT EXISTS per_km_fee_paise INTEGER DEFAULT 500;
ALTER TABLE zones ADD COLUMN IF NOT EXISTS base_distance_km NUMERIC(5,2) DEFAULT 0.00;
ALTER TABLE zones ADD COLUMN IF NOT EXISTS free_delivery_above_paise INTEGER;
ALTER TABLE zones ADD COLUMN IF NOT EXISTS surge_multiplier NUMERIC(3,2) DEFAULT 1.00;
